In [21]:
#numpy is used to do scientific calculations.
#elements of same datatype in the form of array.
#memory consume less as compare to lists
#computation power is more than lists
#numpy is a built-in library which is fast as compare to lists
#homogeneous elements stored in array whereas list stores heterogenous elements

In [23]:
import numpy as np
a=[]
size = int(input("Enter the size: "))
for i in range(size):
    val=int(input("Enter item: "))
    a.append(val)
b=np.array(a)
b

Enter the size:  4
Enter item:  23
Enter item:  12
Enter item:  4
Enter item:  56


array([23, 12,  4, 56])

# How can we check shape and size of an array?

In [26]:
a = np.array([1,34,89,9900])
a

array([   1,   34,   89, 9900])

In [28]:
print("Total Shape=", a.shape)
print("Total Elements=", a.size)

Total Shape= (4,)
Total Elements= 4


In [31]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# row_1 = [1,2,3]
# row_2 = [4,5,6]
# row_3 = [7,8,9]

# col_1 = [1,4,7]
# copl_2 = [2,5,8]
# col_3 = [3,6,9]

In [30]:
print("Total shape=", b.shape)
print("Total Elements=", b.size)

Total shape= (3, 3)
Total Elements= 9


In [ ]:
# iMAGES ===> pixels(0-255) ===> 0px black , 255 px white ==> Normalize(0-1)px 
# Intially weights ===> 0 , 1 
# optimization ===> 0,1 
# matrix ===> n(rows) , n(columns) 
# symmatric Matrix ===> n(rows) = n(columns) 
# Aymmatric Matrix ===> n(rows) !=n(columns) 
# [(1,1) , (2,2) , (3,3) , (4,4)......(n,n)]

# Pre-Defined Function

## (1).zeros()==> It will create an array in which all the elements are 0.

In [7]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [8]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

## (2). ones() ==> It will create an array in which all the elements are 1.

In [9]:
a = np.ones(3)
a

array([1., 1., 1.])

In [11]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
type(a)

numpy.ndarray

In [14]:
a.shape

(2, 3)

In [15]:
a.size

6

## (3). eye()==> In this function diagnoal positional element are 1 and rest all are zero. By default the function is 2D

In [19]:
a =np.eye(4) ###Symetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
a = np.eye(3,4) ####AsymetricMatrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])