In [4]:
import numpy as np

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero . 

In [3]:
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5. randint ==> This function is used to generate a random number between a given range.

## syntax== randint(min_value, max_value, total_numbers)

In [91]:
a =np.random.randint(1,10,3)
a

array([4, 6, 5])

# 6. rand() ==> This function is used to generate a random number between 0 to 1

## syntax == rand(numberofvalues)

In [92]:
a = np.random.rand(5)
a

array([0.01541429, 0.2656121 , 0.82728314, 0.83457956, 0.86875138])

# 7. randn() ==> This function is used to generate a random number from -3 to close 3. This may return positive or negative as well.

## syntax == random.randn(number of values)

In [13]:
a = np.random.randint(1,50,12)
a

array([36, 18,  2, 30, 12, 27, 42,  8,  6, 34, 34, 28])

# Reshaping Data

In [15]:
import numpy as np
a = np.random.randint(1,50,12)
a

array([32, 47, 36, 27, 18, 13, 14, 39, 13, 16, 11, 23])

In [16]:
#n(rows) * n(columns) = n(total_elements)

In [17]:
a.shape

(12,)

In [18]:
a = a.reshape(2,6)
a

array([[32, 47, 36, 27, 18, 13],
       [14, 39, 13, 16, 11, 23]])

In [19]:
a =a.reshape(6,2)
a

array([[32, 47],
       [36, 27],
       [18, 13],
       [14, 39],
       [13, 16],
       [11, 23]])

In [21]:
a =a.reshape(4,3)
a

array([[32, 47, 36],
       [27, 18, 13],
       [14, 39, 13],
       [16, 11, 23]])

In [22]:
a =a.reshape(3,4)
a

array([[32, 47, 36, 27],
       [18, 13, 14, 39],
       [13, 16, 11, 23]])

In [23]:
a =a.reshape(12,1)
a

array([[32],
       [47],
       [36],
       [27],
       [18],
       [13],
       [14],
       [39],
       [13],
       [16],
       [11],
       [23]])

In [24]:
a = a.reshape(10,3)
a

ValueError: cannot reshape array of size 12 into shape (10,3)

# Principal of -1

In [25]:
a = a.reshape(-1, 4)
a

array([[32, 47, 36, 27],
       [18, 13, 14, 39],
       [13, 16, 11, 23]])

# Seed Function() ==> We know that randint function generates random numbers.Everytime we run the program, new set of random number is generated. So, to solve this problem we will use seed function

In [27]:
np.random.seed(5)
a=np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [28]:
np.random.seed(111)
a=np.random.randint(1,100,10)
a

array([85, 85, 85, 87, 20, 42, 67, 83, 41, 72])

# View Vs Copy ==> when we slice a sub-array from an array, it may be done by two ways.

In [30]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b= a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

## copy

In [32]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b= a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [33]:
b

array([0, 0, 0])

## conditonal Selection

In [36]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [38]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [43]:
b = a>10
(a[b])

array([11, 12, 13, 14, 15])

In [44]:
b = a>10
print(a[b])

[11 12 13 14 15]


In [41]:
a[a%2 == 0]
=

[False False False False False False False False False False  True  True
  True  True  True]


## operations on array

In [48]:
a = [1, 2, 3, 4]
a=a*2
print(a)

[1, 2, 3, 4, 1, 2, 3, 4]


In [50]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [51]:
a*2

array([2, 4, 6, 8])

In [53]:
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [54]:
a+2

array([3, 4, 5, 6])

In [55]:
a**2

array([ 1,  4,  9, 16])

In [60]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [61]:
b = np.array([5, 6, 7, 8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [62]:
a+b

array([[ 6,  8],
       [10, 12]])

In [63]:
b-a

array([[4, 4],
       [4, 4]])

In [64]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [65]:
a*b

array([[ 5, 12],
       [21, 32]])

In [66]:
a.dot(b)

array([[19, 22],
       [43, 50]])

# some more important numpy functions

In [67]:
a = np.array([10,20,30,40,50])
np.min(a)

10

In [68]:
np.max(a)

50

In [69]:
np.argmin(a)

0

In [70]:
np.argmax(a)

4

In [71]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [72]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements

In [73]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [74]:
np.random.seed(122)
a = np.random.randint(1,21, 9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [75]:
np.sum(a)

116

# np.unique(arr, return_index =True, return_counts =True)
#### returns 3 array, 1 - the array with unque values, 2. the array with respective index value, 3- the array with counting of frequency

In [76]:
a= np.array([10,20,30,40,10,20,50])
np.unique(a, return_index = True, return_counts =True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [78]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [79]:
b

array([5, 6, 7, 8])

In [80]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Q.1 = Write statement to import numpy ? 

## Q.2 = Create an array using numpy ? 

## Q.3 = Create an array of 10 random integers ?

## Q.4 = Create an array of elements from  10-20? 

## Q.5 = Create an array which contains value 5 , 10 times ? 

## Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

## Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

## Q.8 = Concatenate 2D array horizontally and vertically ? 

In [89]:
#Q.1 = Write statement to import numpy ?
import numpy as np


In [90]:
#Q.2 = Create an array using numpy ?
a = np.array([2,4,6,8,10])
a

array([ 2,  4,  6,  8, 10])

In [88]:
#Q.3 = Create an array of 10 random integers ?
a = np.random.randint(1,100, 10)
a

array([49, 86, 41, 88,  9, 10, 83, 51, 86, 41])

In [96]:
#Q.4 = Create an array of elements from 10-20?
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [99]:
#Q.5 = Create an array which contains value 5 , 10 times ?
a = np.repeat(5,10)
print(a)
a = np.full(10,5)
print(a)

[5 5 5 5 5 5 5 5 5 5]
[5 5 5 5 5 5 5 5 5 5]


In [108]:
#Q.6 = Create a one dimensional array and convert that into 3*3 matrix ?
a = np.arange(1,10)
print(a)
a = a.reshape(3,3)
a

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
#Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?
a = np.random.rand(3,3)
a

array([[0.10903951, 0.01611699, 0.88367645],
       [0.20085906, 0.43598384, 0.60957201],
       [0.81030221, 0.93500256, 0.75083009]])

In [133]:
#Q.8 = Concatenate 2D array horizontally and vertically ?
a = np.random.randint(1,15, 6)
print("a =", a)
a=a.reshape(3,2)
print(a)

b=np.random.randint(1,15,6)
print("b =", b)
b=b.reshape(3,2)
print(b)

hstack = np.hstack((a,b))
print("hstack = ")
print(hstack)

vstack = np.vstack((a,b))
print("vstack =")
print(vstack)

a = [12  9 10 11 11  9]
[[12  9]
 [10 11]
 [11  9]]
b = [ 5  2 10  2 11 10]
[[ 5  2]
 [10  2]
 [11 10]]
hstack = 
[[12  9  5  2]
 [10 11 10  2]
 [11  9 11 10]]
vstack =
[[12  9]
 [10 11]
 [11  9]
 [ 5  2]
 [10  2]
 [11 10]]
