## Q.1 = Write statement to import numpy ? 

## Q.2 = Create an array using numpy ? 

## Q.3 = Create an array of 10 random integers ?

## Q.4 = Create an array of elements from  10-20? 

## Q.5 = Create an array which contains value 5 , 10 times ? 

## Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

## Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

## Q.8 = Concatenate 2D array horizontally and vertically ? 

In [1]:
import numpy as np

In [4]:
a = np.array([2,4,5,7])
a

array([2, 4, 5, 7])

In [6]:
a= np.random.randint(1,20,10)
a

array([12, 11, 16,  5,  5,  8, 18,  7,  3,  9])

In [7]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
a = np.repeat(5,10)
print("a =",a)
b=np.full(10,5)
print("b =",b)

a = [5 5 5 5 5 5 5 5 5 5]
b = [5 5 5 5 5 5 5 5 5 5]


In [20]:
a = np.array([2,4,6,8,10,12,14,16,18])
a = a.reshape(3,3)
a
#a = np.array([2,4,6,8,10,12,14,16,18]).reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
a = np.random.rand(3,3)
a

array([[0.08693154, 0.8701147 , 0.32132401],
       [0.53619003, 0.55813012, 0.25486627],
       [0.64626369, 0.87320423, 0.16894083]])

In [46]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
print("a=",a)
b = np.array([6,5,4,3,2,1]).reshape(2,3)
print("b=",b)
h=np.hstack((a,b))
print("hstack = ")
print(h)
v=np.vstack((a,b))
print("vstack = ")
print(v)

a= [[1 2 3]
 [4 5 6]]
b= [[6 5 4]
 [3 2 1]]
hstack = 
[[1 2 3 6 5 4]
 [4 5 6 3 2 1]]
vstack = 
[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]
